// src/components/contact/ContactPage.vue
<template>
  <!-- The Summoning — contact page with magic circle and sigil nodes -->
  <div class="contact-page">
    <!-- Header -->
    <header class="contact-header">
      <div class="contact-slug">
        <span class="rule" />
        ✦ CONTACT · SUMMON
        <span class="rule" />
      </div>
      <h1 class="contact-title">The Summoning</h1>
      <p class="contact-sub">
        Choose a channel. Trace the sigil. I'll answer.
      </p>
    </header>

    <!-- Desktop: summoning circle -->
    <div class="summoning-wrap" v-if="!isMobile">
      <!-- Charge lines SVG — behind the circle -->
      <svg :width="SIZE" :height="SIZE" class="charge-svg" aria-hidden="true">
        <template v-if="charging && hoveredPos">
          <line
            v-for="(_, i) in Array(5)"
            :key="i"
            :ref="el => { if (el) lineRefs[i] = el as SVGLineElement }"
            :x1="CENTER" :y1="CENTER"
            :x2="hoveredPos[0]" :y2="hoveredPos[1]"
            :stroke="VERMILION" stroke-width="1.5"
            class="cm-flow"
            :style="`animation-delay: ${i * 70}ms`"
          />
          <circle
            :cx="hoveredPos[0]" :cy="hoveredPos[1]"
            :r="DIMS.disc / 2 + 4"
            fill="none" :stroke="VERMILION" stroke-width="1.3"
            class="cm-pulsering"
          />
        </template>
      </svg>

      <!-- The circle -->
      <div class="circle-wrap" ref="circleWrapRef">
        <!-- SVG circle (pure CSS-animated) -->
        <svg
          :width="CIRCLE_SIZE" :height="CIRCLE_SIZE"
          :viewBox="`0 0 ${CIRCLE_SIZE} ${CIRCLE_SIZE}`"
          class="mc-svg" aria-hidden="true"
          :style="`color: ${INK}; animation-duration: ${spinPeriod}s`"
        >
          <style>
            @keyframes mc-rotate { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
            @keyframes mc-rotate-rev { from { transform: rotate(0deg); } to { transform: rotate(-360deg); } }
            @keyframes cm-flow-anim {
              0%,100% { stroke-dashoffset: 24; opacity: 0.5; }
              50% { stroke-dashoffset: 0; opacity: 1; }
            }
            @keyframes cm-pulse {
              0% { r: 20; opacity: 0.7; }
              100% { r: 36; opacity: 0; }
            }
            .cm-flow { stroke-dasharray: 4 4; animation: cm-flow-anim 0.6s linear infinite; }
            .cm-pulsering { animation: cm-pulse 0.8s ease-out infinite; }
          </style>

          <!-- Outer rings (rotating) -->
          <g :style="`transform-origin: ${MC}px ${MC}px; animation: mc-rotate linear infinite; animation-duration: ${spinPeriod}s`">
            <circle :cx="MC" :cy="MC" :r="OUTER_R" stroke="currentColor" stroke-width="0.7" opacity="0.6" fill="none" />
            <circle :cx="MC" :cy="MC" :r="OUTER_R * 0.96" stroke="currentColor" stroke-width="0.3" opacity="0.35" stroke-dasharray="2 4" fill="none" />
            <!-- Ticks -->
            <line v-for="i in 12" :key="i"
              :x1="MC + Math.cos((i-1)/12 * TAU) * OUTER_R * 0.90"
              :y1="MC + Math.sin((i-1)/12 * TAU) * OUTER_R * 0.90"
              :x2="MC + Math.cos((i-1)/12 * TAU) * OUTER_R"
              :y2="MC + Math.sin((i-1)/12 * TAU) * OUTER_R"
              stroke="currentColor" :stroke-width="(i-1) % 3 === 0 ? 0.9 : 0.5" opacity="0.7"
            />
            <!-- Rune text -->
            <defs>
              <path :id="runePathId"
                :d="`M ${MC - RUNE_R} ${MC} A ${RUNE_R} ${RUNE_R} 0 1 1 ${MC - RUNE_R + 0.001} ${MC}`"
              />
            </defs>
            <text :font-size="RUNE_R * 0.085" fill="currentColor" opacity="0.65"
              font-family="'IBM Plex Mono',monospace" letter-spacing="0.04em">
              <textPath :href="`#${runePathId}`">{{ contactRunes }}</textPath>
            </text>
          </g>

          <!-- Inner summoning pentagram (counter-rotating) -->
          <g :style="`transform-origin: ${MC}px ${MC}px; animation: mc-rotate-rev linear infinite; animation-duration: ${spinPeriod * 0.55}s`">
            <!-- Pentagram -->
            <circle :cx="MC" :cy="MC" :r="INNER_R * 0.4" fill="none" stroke="currentColor" stroke-width="0.7" />
            <path :d="pentaPath" fill="none" stroke="currentColor" stroke-width="1.2" />
            <!-- 5 satellite nodes -->
            <g v-for="(pt, i) in satPts" :key="i">
              <line :x1="pentaPts[i][0]" :y1="pentaPts[i][1]" :x2="pt[0]" :y2="pt[1]" stroke="currentColor" stroke-width="0.6" />
              <circle :cx="pt[0]" :cy="pt[1]" :r="INNER_R * 0.14" fill="none" stroke="currentColor" stroke-width="0.9" />
              <circle class="mc-summon-node" :cx="pt[0]" :cy="pt[1]" r="1.6" fill="currentColor" />
            </g>
          </g>
        </svg>
      </div>

      <!-- Core monogram (fixed, centred over the spinning circle) -->
      <div class="monogram" :class="{ charging }">
        <div class="monogram-ring" :class="{ charging }">
          <span class="monogram-text">CJ-Uy</span>
        </div>
        <div class="monogram-label" :style="{ color: charging ? VERMILION : '#888' }">
          {{ charging ? 'channelling' : 'summon' }}
        </div>
      </div>

      <!-- Sigil nodes -->
      <component
        v-for="ch in CHANNELS" :key="ch.id"
        :is="ch.href ? 'a' : 'div'"
        v-bind="ch.href ? { href: ch.href, target: ch.href.startsWith('http') ? '_blank' : undefined, rel: 'noopener noreferrer' } : {}"
        class="sigil-node"
        :style="sigilStyle(ch)"
        @mouseenter="hovered = ch.id"
        @mouseleave="hovered = null"
      >
        <!-- Disc -->
        <div class="sigil-disc" :class="{ live: hovered === ch.id && ch.href }" :style="discStyle(ch)">
          {{ ch.sigil }}
        </div>
        <!-- Label -->
        <div class="sigil-label" :style="labelStyle(ch)">
          <div class="sigil-label-name" :style="{ color: hovered === ch.id ? VERMILION : INK }">
            {{ ch.label }}
          </div>
          <div class="sigil-label-handle">{{ ch.handle }}</div>
        </div>
      </component>
    </div>

    <!-- Mobile: stacked list -->
    <div v-else class="mobile-channels">
      <a
        v-for="ch in CHANNELS" :key="ch.id"
        :href="ch.href" target="_blank" rel="noopener noreferrer"
        class="mobile-channel"
      >
        <span class="mobile-sigil" :class="{ accent: ch.accent }">{{ ch.sigil }}</span>
        <div>
          <div class="mobile-channel-label">{{ ch.label }}</div>
          <div class="mobile-channel-handle">{{ ch.handle }}</div>
        </div>
        <span class="mobile-arrow">↗</span>
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, useId } from 'vue';

const INK = '#0a0a0a';
const VERMILION = '#dc3522';
const TAU = Math.PI * 2;

const CONTACT_RUNES = '· VOCA · SCRIBE · INVOCO · RESPONDEO · COLLOQVIVM · SOCIETAS · ADSVM ';

const CHANNELS = [
  { id: 'email',    sigil: '✉',  label: 'Email',    handle: 'charlesjoshuauy@gmail.com',     href: 'mailto:charlesjoshuauy@gmail.com', angle: -90, accent: true },
  { id: 'github',   sigil: 'GH', label: 'GitHub',   handle: 'CJ-Uy',                          href: 'https://github.com/CJ-Uy',         angle: -30 },
  { id: 'linkedin', sigil: 'in', label: 'LinkedIn', handle: 'in/charles-joshua-uy',            href: 'https://www.linkedin.com/in/charles-joshua-uy-920826274/', angle: 30 },
  { id: 'phone',    sigil: '✆',  label: 'Phone',    handle: '+63 917 150 4686',                href: 'tel:+639171504686',                angle: 90 },
  { id: 'cv',       sigil: 'CV', label: 'CV',       handle: 'Open PDF ↗',                     href: 'https://cv.cjuy.dev',              angle: 150 },
  { id: 'facebook', sigil: 'f',  label: 'Facebook', handle: '/charlesjoshua.uy',               href: 'https://facebook.com/charlesjoshua.uy', angle: 210 },
] as const;

// Layout dimensions
const SIZE = 680;
const CIRCLE_SIZE = 372;
const CENTER = SIZE / 2;
const MC = CIRCLE_SIZE / 2;
const OUTER_R = MC * 0.88;
const RUNE_R = MC * 0.78;
const INNER_R = MC * 0.58;
const DIMS = { nodeR: 238, disc: 52, labelGap: 16 };

// Pentagram geometry (inner shape)
function polarPts(cx: number, cy: number, r: number, n: number, start = -Math.PI / 2) {
  return Array.from({ length: n }, (_, i) => {
    const a = start + (i / n) * TAU;
    return [cx + Math.cos(a) * r, cy + Math.sin(a) * r] as [number, number];
  });
}
const pentaPts = polarPts(MC, MC, INNER_R * 0.4, 5);
const satPts   = polarPts(MC, MC, INNER_R * 0.78, 5);
const pentaPath = `M ${pentaPts[0][0]} ${pentaPts[0][1]} L ${pentaPts[2][0]} ${pentaPts[2][1]} L ${pentaPts[4][0]} ${pentaPts[4][1]} L ${pentaPts[1][0]} ${pentaPts[1][1]} L ${pentaPts[3][0]} ${pentaPts[3][1]} Z`;

// Reactive state
const hovered = ref<string | null>(null);
const isMobile = ref(false);
const lineRefs = ref<SVGLineElement[]>([]);
const circleWrapRef = ref<HTMLElement | null>(null);

const runePathId = `rune-path-${Math.random().toString(36).slice(2, 8)}`;
const contactRunes = CONTACT_RUNES.repeat(8);

const charging = computed(() =>
  !!CHANNELS.find((c) => c.id === hovered.value && c.href),
);

const hoveredPos = computed<[number, number] | null>(() => {
  if (!charging.value) return null;
  const ch = CHANNELS.find((c) => c.id === hovered.value)!;
  const rad = (ch.angle * Math.PI) / 180;
  return [CENTER + Math.cos(rad) * DIMS.nodeR, CENTER + Math.sin(rad) * DIMS.nodeR];
});

// Spin period: normal 150s, charging 36s (4.2× faster)
const spinPeriod = computed(() => charging.value ? 36 : 150);

// Sigil node positioning
function sigilStyle(ch: typeof CHANNELS[number]): Record<string, string> {
  const rad = (ch.angle * Math.PI) / 180;
  const nx = Math.cos(rad) * DIMS.nodeR;
  const ny = Math.sin(rad) * DIMS.nodeR;
  return {
    position: 'absolute',
    left: `${CENTER + nx}px`,
    top: `${CENTER + ny}px`,
    transform: 'translate(-50%, -50%)',
    textDecoration: 'none',
    cursor: ch.href ? 'pointer' : 'default',
    zIndex: '4',
  };
}

function discStyle(ch: typeof CHANNELS[number]): Record<string, string> {
  const live = hovered.value === ch.id && ch.href;
  return {
    width: `${DIMS.disc}px`, height: `${DIMS.disc}px`,
    borderRadius: '50%',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    background: live ? VERMILION : '#faf9f6',
    border: `1.5px solid ${live ? VERMILION : INK}`,
    color: live ? '#faf9f6' : INK,
    boxShadow: live ? '0 4px 14px rgba(220,53,34,0.3)' : `0 2px 0 ${INK}`,
    fontFamily: ch.sigil.length > 1 ? "'IBM Plex Mono', monospace" : 'Georgia, serif',
    fontSize: `${ch.sigil.length > 1 ? DIMS.disc * 0.34 : DIMS.disc * 0.46}px`,
    fontWeight: '600',
    transition: 'all 220ms cubic-bezier(0.34,1.1,0.64,1)',
    transform: live ? 'scale(1.12)' : 'scale(1)',
    userSelect: 'none',
  };
}

function labelStyle(ch: typeof CHANNELS[number]): Record<string, string> {
  const rad = (ch.angle * Math.PI) / 180;
  const ux = Math.cos(rad), uy = Math.sin(rad);
  const labelW = 132, labelH = 44;
  const proj = Math.abs(ux) * (labelW / 2) + Math.abs(uy) * (labelH / 2);
  const labelDist = DIMS.nodeR + DIMS.disc / 2 + DIMS.labelGap + proj;
  const lx = Math.cos(rad) * labelDist - Math.cos(rad) * DIMS.nodeR;
  const ly = Math.sin(rad) * labelDist - Math.sin(rad) * DIMS.nodeR;
  return {
    position: 'absolute',
    left: `${lx}px`, top: `${ly}px`,
    transform: 'translate(-50%, -50%)',
    width: `${labelW}px`, textAlign: 'center', lineHeight: '1.25',
    pointerEvents: 'none',
  };
}

// RAF loop for charge-line endpoints
let raf = 0;
function animLoop() {
  if (charging.value && circleWrapRef.value) {
    const crect = circleWrapRef.value.getBoundingClientRect();
    const ch = CHANNELS.find((c) => c.id === hovered.value);
    if (ch && hoveredPos.value) {
      const tx = hoveredPos.value[0], ty = hoveredPos.value[1];
      const nodes = circleWrapRef.value.querySelectorAll<SVGCircleElement>('.mc-summon-node');
      nodes.forEach((nd, i) => {
        const ln = lineRefs.value[i];
        if (!ln) return;
        const nr = nd.getBoundingClientRect();
        const nx = nr.left + nr.width / 2 - crect.left + CENTER - CIRCLE_SIZE / 2;
        const ny = nr.top + nr.height / 2 - crect.top + CENTER - CIRCLE_SIZE / 2;
        ln.setAttribute('x1', nx.toFixed(1));
        ln.setAttribute('y1', ny.toFixed(1));
        ln.setAttribute('x2', tx.toFixed(1));
        ln.setAttribute('y2', ty.toFixed(1));
      });
    }
  }
  raf = requestAnimationFrame(animLoop);
}

onMounted(() => {
  isMobile.value = window.innerWidth < 640;
  window.addEventListener('resize', () => { isMobile.value = window.innerWidth < 640; });
  raf = requestAnimationFrame(animLoop);
});

onUnmounted(() => cancelAnimationFrame(raf));
</script>

<style scoped>
.contact-page {
  min-height: 100vh;
  background: var(--paper);
  color: var(--ink);
  display: flex;
  flex-direction: column;
  align-items: center;
}

/* ── Header ──────────────────────────────────────────────────── */
.contact-header {
  text-align: center;
  padding: 7rem 2rem 2rem;
}

.contact-slug {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  font-family: 'IBM Plex Mono', monospace;
  font-size: 9.5px;
  font-weight: 700;
  letter-spacing: 0.32em;
  text-transform: uppercase;
  opacity: 0.5;
  margin-bottom: 12px;
}

.rule {
  display: inline-block;
  width: 20px;
  height: 1px;
  background: var(--ink);
  opacity: 0.6;
}

.contact-title {
  font-family: 'Instrument Serif', Georgia, serif;
  font-size: clamp(2.2rem, 5.5vw, 3.8rem);
  font-weight: 400;
  letter-spacing: -0.04em;
  color: var(--ink);
}

.contact-sub {
  font-family: 'IBM Plex Mono', monospace;
  font-size: 0.72rem;
  color: #6a6a68;
  margin-top: 14px;
  max-width: 32ch;
  margin-inline: auto;
  line-height: 1.6;
}

/* ── Summoning wrap ───────────────────────────────────────────── */
.summoning-wrap {
  position: relative;
  width: 680px;
  height: 680px;
  margin: 2rem auto 4rem;
  flex-shrink: 0;
}

.charge-svg {
  position: absolute;
  inset: 0;
  pointer-events: none;
  overflow: visible;
  z-index: 0;
}

.circle-wrap {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  z-index: 1;
}

.mc-svg {
  display: block;
}

/* ── Monogram ─────────────────────────────────────────────────── */
.monogram {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
  pointer-events: none;
  z-index: 3;
}

.monogram-ring {
  width: 102px;
  height: 102px;
  border-radius: 50%;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--paper);
  border: 1.5px solid var(--ink);
  box-shadow: 0 2px 0 var(--ink);
  transition: border-color 220ms ease, box-shadow 260ms ease;
}

.monogram-ring.charging {
  border-color: var(--vermilion);
  box-shadow: 0 0 0 4px rgba(220,53,34,0.10), 0 2px 0 var(--ink);
}

.monogram-text {
  font-family: 'Instrument Serif', Georgia, serif;
  font-size: 27px;
  color: var(--ink);
  letter-spacing: -0.01em;
  white-space: nowrap;
}

.monogram-label {
  font-family: 'IBM Plex Mono', monospace;
  font-size: 8.5px;
  font-weight: 700;
  letter-spacing: 0.3em;
  margin-top: 11px;
  text-transform: uppercase;
  transition: color 200ms ease;
}

/* ── Sigil nodes ──────────────────────────────────────────────── */
.sigil-node {
  position: absolute;
}

.sigil-disc {
  cursor: pointer;
}

.sigil-label-name {
  font-family: 'IBM Plex Mono', monospace;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  transition: color 200ms ease;
}

.sigil-label-handle {
  font-family: 'Instrument Serif', Georgia, serif;
  font-style: italic;
  font-size: 14px;
  color: #555;
  margin-top: 1px;
  white-space: nowrap;
}

/* ── Mobile channels ──────────────────────────────────────────── */
.mobile-channels {
  width: 100%;
  max-width: 420px;
  padding: 1rem 1.5rem 4rem;
  display: flex;
  flex-direction: column;
  gap: 0;
}

.mobile-channel {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 18px 0;
  border-bottom: 1px solid var(--mute-2);
  text-decoration: none;
  color: var(--ink);
  transition: background 120ms;
}

.mobile-channel:hover { background: rgba(10,10,10,0.03); }

.mobile-sigil {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  border: 1.5px solid var(--ink);
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: 'IBM Plex Mono', monospace;
  font-size: 13px;
  font-weight: 600;
  flex-shrink: 0;
}

.mobile-sigil.accent {
  border-color: var(--vermilion);
  color: var(--vermilion);
}

.mobile-channel-label {
  font-family: 'IBM Plex Mono', monospace;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}

.mobile-channel-handle {
  font-family: 'Instrument Serif', Georgia, serif;
  font-style: italic;
  font-size: 14px;
  color: #555;
  margin-top: 2px;
}

.mobile-arrow {
  margin-left: auto;
  font-family: 'IBM Plex Mono', monospace;
  font-size: 14px;
  opacity: 0.4;
}
</style>

// src/components/contact/ContactPage.tsx
/**
 * ContactPage — faithful port of contact-page.jsx from the design bundle.
 * CSS classes (.wp-*, .ph-*, .cm-*) are defined in contact.astro <style is:global>.
 * Framework: React (matches the design's React JSX).
 */

import React, { useState, useEffect, useRef } from 'react';
import MagicCircle from '../shared/MagicCircle';

const INKC = '#0a0a0a';
const VERMC = '#dc3522';

const CONTACT_RUNES = '· VOCA · SCRIBE · INVOCO · RESPONDEO · COLLOQVIVM · SOCIETAS · ADSVM ';

const CHANNELS = [
  { id: 'email',    sigil: '✉',  label: 'Email',             handle: 'charlesjoshuauy@gmail.com',     href: 'mailto:charlesjoshuauy@gmail.com',                      angle: -90, accent: true  },
  { id: 'github',   sigil: 'GH', label: 'GitHub',            handle: 'CJ-Uy',                          href: 'https://github.com/CJ-Uy',                              angle: -30 },
  { id: 'linkedin', sigil: 'in', label: 'LinkedIn',          handle: 'in/charles-joshua-uy',            href: 'https://www.linkedin.com/in/charles-joshua-uy-920826274/', angle: 30 },
  { id: 'phone',    sigil: '✆',  label: 'Phone',             handle: '+63 917 150 4686',                href: 'tel:+639171504686',                                     angle: 90  },
  { id: 'cv',       sigil: 'CV', label: 'Curriculum Vitae',  handle: 'Open PDF ↗',                     href: 'https://cv.cjuy.dev',                                   angle: 150 },
  { id: 'facebook', sigil: 'f',  label: 'Facebook',          handle: '/charlesjoshua.uy',               href: 'https://facebook.com/charlesjoshua.uy',                 angle: 210 },
] as const;

type Channel = typeof CHANNELS[number];

// ── Sigil node positioned on circle perimeter ─────────────────────
function SigilNode({ ch, hovered, onHover, dims }: {
  ch: Channel;
  hovered: string | null;
  onHover: (id: string | null) => void;
  dims: { nodeR: number; disc: number; labelGap: number };
}) {
  const { nodeR, disc, labelGap } = dims;
  const rad = (ch.angle * Math.PI) / 180;
  const ux = Math.cos(rad), uy = Math.sin(rad);
  const nx = ux * nodeR, ny = uy * nodeR;
  const labelW = 132, labelH = 44;
  const proj = Math.abs(ux) * (labelW / 2) + Math.abs(uy) * (labelH / 2);
  const labelDist = nodeR + disc / 2 + labelGap + proj;
  const lx = ux * labelDist, ly = uy * labelDist;
  const isHover = hovered === ch.id;
  const live = isHover && ch.href;
  const Tag = ch.href ? 'a' : 'div';
  const props = ch.href
    ? { href: ch.href, target: (ch.href.startsWith('http') ? '_blank' : undefined) as string | undefined, rel: 'noopener noreferrer' }
    : {};

  return (
    <Tag
      {...props}
      onMouseEnter={() => onHover(ch.id)}
      onMouseLeave={() => onHover(null)}
      style={{
        position: 'absolute', left: '50%', top: '50%',
        transform: 'translate(-50%, -50%)',
        textDecoration: 'none', cursor: ch.href ? 'pointer' : 'default',
        pointerEvents: 'auto', zIndex: 4,
      }}
    >
      {/* disc */}
      <div style={{
        position: 'absolute', left: nx, top: ny, transform: `translate(-50%, -50%) scale(${live ? 1.12 : 1})`,
        width: disc, height: disc, borderRadius: '50%',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        background: live ? VERMC : '#faf9f6',
        border: `1.5px solid ${live ? VERMC : INKC}`,
        color: live ? '#faf9f6' : INKC,
        boxShadow: live ? '0 4px 14px rgba(220,53,34,0.3)' : `0 2px 0 ${INKC}`,
        fontFamily: ch.sigil.length > 1 ? "'IBM Plex Mono', monospace" : 'Georgia, serif',
        fontSize: ch.sigil.length > 1 ? disc * 0.34 : disc * 0.46,
        fontWeight: 600, transition: 'all 220ms cubic-bezier(0.34,1.1,0.64,1)',
        userSelect: 'none',
      }}>{ch.sigil}</div>
      {/* label */}
      <div style={{
        position: 'absolute', left: lx, top: ly,
        transform: 'translate(-50%, -50%)',
        width: labelW, textAlign: 'center', lineHeight: 1.25,
      }}>
        <div style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase', color: live ? VERMC : INKC, transition: 'color 200ms ease' }}>{ch.label}</div>
        <div style={{ fontFamily: "'Instrument Serif', Georgia, serif", fontStyle: 'italic', fontSize: 14, color: '#555', marginTop: 1, whiteSpace: 'nowrap' }}>{ch.handle}</div>
      </div>
    </Tag>
  );
}

// ── Desktop summoning apparatus ───────────────────────────────────
function SummoningCircle() {
  const [hovered, setHovered] = useState<string | null>(null);
  const hoveredRef = useRef<string | null>(null);
  useEffect(() => { hoveredRef.current = hovered; }, [hovered]);

  const charging = !!CHANNELS.find((x) => x.id === hovered && x.href);

  const size = 680;
  const circleSize = 372;
  const dims = { nodeR: 238, disc: 52, labelGap: 16 };
  const c = size / 2;
  const N = 5;

  const wrapRef = useRef<HTMLDivElement>(null);
  const lineRefs = useRef<(SVGLineElement | null)[]>([]);
  const animsRef = useRef<Animation[] | null>(null);
  const rateRef = useRef(1);

  let hp: [number, number] | null = null;
  if (charging) {
    const ch = CHANNELS.find((x) => x.id === hovered)!;
    const r = (ch.angle * Math.PI) / 180;
    hp = [c + Math.cos(r) * dims.nodeR, c + Math.sin(r) * dims.nodeR];
  }

  useEffect(() => {
    let raf: number;
    const tick = () => {
      try {
        const hv = hoveredRef.current;
        const ch = CHANNELS.find((x) => x.id === hv && x.href);
        const targetRate = ch ? 4.2 : 1;
        rateRef.current += (targetRate - rateRef.current) * 0.08;

        if ((!animsRef.current || !animsRef.current.length) && wrapRef.current) {
          const list = wrapRef.current.getAnimations({ subtree: true });
          if (list && list.length) animsRef.current = list;
        }
        if (animsRef.current) {
          for (const a of animsRef.current) { try { a.playbackRate = rateRef.current; } catch (_) {} }
        }

        if (ch && wrapRef.current) {
          const crect = wrapRef.current.parentElement!.getBoundingClientRect();
          const r = (ch.angle * Math.PI) / 180;
          const tx = c + Math.cos(r) * dims.nodeR, ty = c + Math.sin(r) * dims.nodeR;
          const nodes = wrapRef.current.querySelectorAll<SVGCircleElement>('.mc-summon-node');
          for (let i = 0; i < N; i++) {
            const ln = lineRefs.current[i];
            const nd = nodes[i];
            if (ln && nd) {
              const nr = nd.getBoundingClientRect();
              const nx = nr.left + nr.width / 2 - crect.left;
              const ny = nr.top + nr.height / 2 - crect.top;
              ln.setAttribute('x1', nx.toFixed(2)); ln.setAttribute('y1', ny.toFixed(2));
              ln.setAttribute('x2', tx.toFixed(2)); ln.setAttribute('y2', ty.toFixed(2));
            }
          }
        }
      } catch (_) {}
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [c]);

  return (
    <div style={{ position: 'relative', width: size, height: size, margin: '0 auto' }}>
      {/* charge lines */}
      <svg width={size} height={size} style={{ position: 'absolute', inset: 0, pointerEvents: 'none', overflow: 'visible', zIndex: 0 }} aria-hidden="true">
        {charging && Array.from({ length: N }, (_, i) => (
          <line key={i} ref={(el) => { lineRefs.current[i] = el; }}
            x1={c} y1={c} x2={hp ? hp[0] : c} y2={hp ? hp[1] : c}
            stroke={VERMC} strokeWidth="1.5" className="cm-flow"
            style={{ animationDelay: `${i * 70}ms` }}
          />
        ))}
        {hp && <circle cx={hp[0]} cy={hp[1]} r={dims.disc / 2 + 4} fill="none" stroke={VERMC} strokeWidth="1.3" className="cm-pulsering" />}
      </svg>

      {/* the circle */}
      <div ref={wrapRef} style={{ position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)', zIndex: 1 }}>
        <MagicCircle variant="summoning" size={circleSize}
          rotateSpeed={150} innerRotateSpeed={80}
          reverseInner runes runeText={CONTACT_RUNES} showCardinals
          style={{ color: INKC }} />
      </div>

      {/* core monogram */}
      <div style={{ position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)', textAlign: 'center', pointerEvents: 'none', zIndex: 3 }}>
        <div style={{
          width: 102, height: 102, borderRadius: '50%', margin: '0 auto',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          background: '#faf9f6',
          border: `1.5px solid ${charging ? VERMC : INKC}`,
          boxShadow: charging ? `0 0 0 4px rgba(220,53,34,0.10), 0 2px 0 ${INKC}` : `0 2px 0 ${INKC}`,
          transition: 'border-color 220ms ease, box-shadow 260ms ease',
        }}>
          <span style={{ fontFamily: "'Instrument Serif', Georgia, serif", fontSize: 27, color: INKC, letterSpacing: '-0.01em', whiteSpace: 'nowrap' }}>CJ-Uy</span>
        </div>
        <div style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: 8.5, fontWeight: 700, letterSpacing: '0.3em', color: charging ? VERMC : '#888', marginTop: 11, textTransform: 'uppercase', transition: 'color 200ms ease' }}>
          {charging ? 'channelling' : 'summon'}
        </div>
      </div>

      {/* nodes */}
      {CHANNELS.map((ch) => <SigilNode key={ch.id} ch={ch} hovered={hovered} onHover={setHovered} dims={dims} />)}
    </div>
  );
}

// ── Mobile stacked list ───────────────────────────────────────────
function SummoningList() {
  return (
    <div style={{ maxWidth: 420, margin: '0 auto', width: '100%' }}>
      <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 34 }}>
        <MagicCircle variant="summoning" size={180} rotateSpeed={150} innerRotateSpeed={80} reverseInner runeText={CONTACT_RUNES} showCardinals style={{ color: INKC }} />
      </div>
      <div style={{ display: 'flex', flexDirection: 'column' }}>
        {CHANNELS.map((ch) => {
          const Tag = ch.href ? 'a' : 'div';
          const props = ch.href ? { href: ch.href, target: (ch.href.startsWith('http') ? '_blank' : undefined) as string | undefined, rel: 'noopener noreferrer' } : {};
          return (
            <Tag key={ch.id} {...props} className="cm-row" style={{ textDecoration: 'none', color: INKC }}>
              <span className="cm-row-disc" style={{ fontFamily: ch.sigil.length > 1 ? "'IBM Plex Mono', monospace" : 'Georgia, serif', fontSize: ch.sigil.length > 1 ? 15 : 20 }}>{ch.sigil}</span>
              <span style={{ flex: 1 }}>
                <span style={{ display: 'block', fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase' }}>{ch.label}</span>
                <span style={{ display: 'block', fontFamily: "'Instrument Serif', Georgia, serif", fontStyle: 'italic', fontSize: 15, color: '#555' }}>{ch.handle}</span>
              </span>
              {ch.href && <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: 13, opacity: 0.5 }}>↗</span>}
            </Tag>
          );
        })}
      </div>
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────
export default function ContactPage() {
  const [narrow, setNarrow] = useState(
    typeof window !== 'undefined' && window.innerWidth < 820,
  );
  useEffect(() => {
    const on = () => setNarrow(window.innerWidth < 820);
    window.addEventListener('resize', on);
    return () => window.removeEventListener('resize', on);
  }, []);

  return (
    <>
      <nav className="wp-nav">
        <a href="/" className="wp-brand">atelier</a>
        <div className="wp-links">
          <a href="/" className="wp-link">Home</a>
          <a href="/works" className="wp-link">Works</a>
          <a href="/contact" className="wp-link active">Contact</a>
        </div>
      </nav>

      <header className="ph-header">
        <div className="ph-circlemark">
          <MagicCircle variant="summoning" size={104} rotateSpeed={140} innerRotateSpeed={70} reverseInner runeText={CONTACT_RUNES} style={{ color: INKC }} />
        </div>
        <div className="ph-eyebrow">✦ THE SUMMONING · RITE NO. VIII ✦</div>
        <h1 className="ph-title">Contact Me</h1>
        <p className="ph-sub">Every circle on this site was cast for something. This one summons me — trace a sigil to open the channel.</p>
        <div className="cm-status">
          <span className="cm-dot" />
          OPEN TO OPPORTUNITIES &amp; COLLABORATIONS
        </div>
      </header>

      <main className="cm-stage">
        {narrow ? <SummoningList /> : <SummoningCircle />}
      </main>

      <footer className="cm-foot">
        <span /><span>RESPONDS WITHIN A MOON&apos;S TURN · TYPICALLY ~48H</span><span />
      </footer>
    </>
  );
}
